kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: deps & tests
    commands:
      - npm install --ignore-scripts
      - npm run prd

trigger:
  branch:
    - master
    - stg
  event:
    - push
    - pull_request
